### ISSUE TITLE
SDK Swallows Errors instead of throwing

### ISSUE THREAD

**Issue by ericlathrop** [LitleCo/litle-sdk-for-ruby#15]
When I make a registerTokenRequest and get an error, the SDK swallows the error and just returns an empty string as the response. I expect the SDK to raise an exception with the error message and error code.

Here is an example XML response that doesn't generate an error, but should:
```xml
<litleOnlineResponse version="8.19" xmlns="http://www.litle.com/schema" response="0" message="Valid Format">
 <registerTokenResponse reportGroup="IK">      
  <litleTxnId>83001039621080053</litleTxnId>
  <response>878</response>
  <responseTime>2014-06-20T15:02:13</responseTime>
  <message>Expired paypage registration id</message>
 </registerTokenResponse>
</litleOnlineResponse>
```

**Comment by leonli0326** [comment]
This is a valid response XML for SDK to create response object, SDK would raise exception on invalid/corrupted XML response but not ones in valid format. If the response XML is empty string, it's like to be other error than the response parser in SDK.
