### ISSUE TITLE
register_token_request only returns empty string

### ISSUE THREAD

**Issue by ericlathrop** [LitleCo/litle-sdk-for-ruby#16]
When I make a call to register_token_request, and the server returns successful XML with a token, register_token_request just returns an empty string, and never the token.

Here's an example successful XML response from the server:
```xml
<litleOnlineResponse version="8.19" xmlns="http://www.litle.com/schema" response="0" message="Valid Format">
 <registerTokenResponse reportGroup="IK">
  <litleTxnId>83001040162571435</litleTxnId>
  <litleToken>1122000136140003</litleToken>
  <response>802</response>
  <responseTime>2014-06-20T16:50:49</responseTime>
  <message>Account number was previously registered</message>
  <bin>511201</bin>
  <type>MC</type>
 </registerTokenResponse>
</litleOnlineResponse>
```

**Comment by leonli0326** [comment]
The response XML is correctly generated in both 8.29.0 and 9.3.0 release, for test cases please refer to test/functional/test_token.

**Comment by KMontag42** [comment]
these test cases are pretty terrible. especially considering the SDK does not actually throw these errors. Empty strings everywhere...

I am having the same issue as OP here is an example (i took the test data from their PDF technical specification guide):
```ruby
[8] pry(main)> r = lor.register_token_request({'orderId' => 50, 'accountNumber' => 4457119922390123, 'cardValidationNumber' => 123})
<litleOnlineRequest merchantId="01141791" merchantSdk="Ruby;9.3.2" version="9.3" xmlns="http://www.litle.com/schema"><authentication><user>SKILLZ</user><password>cert7ds4</password></authentication><registerTokenRequest reportGroup="Default Report Group"><orderId>50</orderId><accountNumber>4457119922390123</accountNumber></registerTokenRequest></litleOnlineRequest>
<litleOnlineResponse version="9.3" xmlns="http://www.litle.com/schema"
    response="0" message="Valid Format">
    <registerTokenResponse reportGroup="Default Report Group">
        <litleTxnId>82915132849439552</litleTxnId>
        <orderId>50</orderId>
        <litleToken>1111000186030123</litleToken>
        <response>801</response>
        <responseTime>2015-04-06T20:23:09</responseTime>
        <message>Account number was successfully registered</message>
        <bin>445711</bin>
        <type>VI</type>
    </registerTokenResponse>
</litleOnlineResponse>

=> ""
```

**Comment by litleSDK** [comment]
Hi Montag,

I have seen your replies on GitHub issues. However, From the current information you have provided, I can’t reproduce your problem , everything seems working. For us to further help you on your issue, please provide some more specific information, such as the version of SDK you are using , the version of Xml-mapper of your gem. And Also I can see that you can successfully get our litleOnlineResponse xml.  If you want to access the reponse object, just try some as ‘Print r.message’. In your case, it would print “Valid Format” for you.

Li
