### ISSUE TITLE
LitleBatchRequest#account_update: NoMethodError: undefined method `first' for :else:Symbol

### ISSUE THREAD

**Issue by wojnosystems** [LitleCo/litle-sdk-for-ruby#17]
I'm getting an exception thrown that I can trace down to a line 44 in: https://github.com/LitleCo/litle-sdk-for-ruby/blob/master/lib/XMLFields.rb

Looks as though you've created an extension to the XML-Mapper gem you're using to serialize between XML.

This throws the following exception: "NoMethodError: undefined method `first' for :else:Symbol".

This is occurring when I call: "account_update(options)" (see: https://github.com/LitleCo/litle-sdk-for-ruby/blob/master/lib/LitleBatchRequest.rb:311)

I created a batch, like usual, then called:

account_update( {
   'token' => {
       'litleToken' => old_token
    }
} )

It doesn't appear as though this case is tested in test/unit/test_LitleAUBatch.rb

**Comment by leonli0326** [comment]
The bug in XMLFields is fixed in newest 9.3.1 and 8.29.1 versions
