### ISSUE TITLE
using xml-mapping version 0.10.0 causes XML error in LitleOnlineRequest

### ISSUE THREAD

**Issue by daveande** [LitleCo/litle-sdk-for-ruby#19]
The xml-mapping gem was updated to 0.10.0 today and it causes a "Wrong number of arguments (0 for 1)" error when submitting a LitleOnlineRequest.new.sale(). To fix, I've specified xml-mapping to version 0.9.1 in my Gemfile.

I think you should specify the xml-mapping version when declaring that as a dependency in your Gem.

**Comment by ryanaking** [comment]
I ran into this issue also, what is the fix (besides downgrading to 0.9.1)?

**Comment by leonli0326** [comment]
Fixed in 8.29.0 and 9.3.0 release

**Comment by KMontag42** [comment]
still getting this issue with v9.3.2

**Comment by litao-vantiv** [comment]
Hi Montag,

I have seen your replies on GitHub issues. However, From the current information you have provided, I can’t reproduce your problem , everything seems working. For us to further help you on this issue, please provide some more specific information, such as the version of SDK you are using , the version of Xml-mapper of your gem, the full test code you are using. And Also I can see that you can successfully get our litleOnlineResponse xml.  If you want to access the reponse object, just try some as ‘Print r.message’. In your case, it would print “Valid Format” for you.  
Please contact us at sdksupport@litle.com

**Comment by KMontag42** [comment]
Thanks for getting back to me!!

The majority of issues I had were solved by downgrading the SDK itself. 

However this issue persisted. The only way to fix it was to downgrade the XML gem to the older version. 

Not the end of the world. Thanks again!

**Comment by litao-vantiv** [comment]
Currently we are supporting gem xml-mapping 0.10.0. If you have any further problem, feel free to contact us.

Li

**Comment by robg** [comment]
I'm seeing this issue with LitleOnline 9.3.2 when used in conjunction with  ActiveSupport 3.2.12.  If this was fixed in the 9.3.0 release, can you point to the commit that fixed it?  Based on the code currently on master, it still appears to be broken.

**Comment by leonli0326** [comment]
fixed in: commit 04080f425611baa021f86ef3f003dbe8b09e099a 
file: lib/XMLFields.rb
please noted that this change is accommodated to the changes in xml-mapping 0.10.0, it is possible that the different version of xml-mapping would cause problems.
